# -*- coding: utf-8 -*-
"""VidyAI++

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gg3Y6VoNU4VBZmEwI0aXK6UH-CiByEHt
"""

from IPython.core.display import display, HTML

html_code = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>VidyAI++ – AI Tutoring Platform</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', sans-serif; background: #f5f8fa; color: #333; line-height: 1.6; }
    header { background: #1e3a8a; color: white; padding: 30px 20px; text-align: center; }
    nav { background: #2563eb; text-align: center; padding: 10px 0; }
    nav ul { list-style: none; }
    nav ul li { display: inline-block; margin: 0 15px; }
    nav ul li a { color: white; text-decoration: none; font-weight: bold; }
    section { padding: 30px 20px; max-width: 900px; margin: auto; }
    section h2 { margin-bottom: 15px; font-size: 1.8rem; color: #1e40af; }
    section ul li { margin-bottom: 10px; font-size: 1.1rem; }
    a { color: #2563eb; }
    footer { text-align: center; padding: 20px; background: #1e3a8a; color: white; margin-top: 40px; }
  </style>
</head>
<body>
  <header>
    <h1>VidyAI++</h1>
    <p>Multilingual AI Tutoring & Mentorship for BPL Students</p>
  </header>
  <nav>
    <ul>
      <li><a href="#objective">Objective</a></li>
      <li><a href="#features">Key Features</a></li>
      <li><a href="#contact">Contact</a></li>
    </ul>
  </nav>
  <section id="objective">
    <h2>Objective</h2>
    <p>
      Design an AI-powered, multilingual, inclusive web platform to provide
      personalized education and mentorship to underprivileged students in
      government schools across India. VidyAI++ aligns with NEP guidelines and
      uses cutting-edge AI for interactive and accessible learning.
    </p>
  </section>
  <section id="features">
    <h2>Key Features</h2>
    <ul>
      <li>🧠 <strong>AI Tutoring:</strong> Localized, text & speech-based learning with Gemini/GPT</li>
      <li>📈 <strong>Adaptive Content:</strong> Adjusts difficulty with reinforcement learning</li>
      <li>👀 <strong>Vision Analysis:</strong> Emotion detection, eye-tracking with DeepFace + OpenCV</li>
      <li>🤝 <strong>Mentor Matching:</strong> Connects students with volunteers & NGOs</li>
      <li>🎨 <strong>Persona Engine:</strong> Visual, auditory, kinesthetic learning modes</li>
      <li>🏅 <strong>Gamified Learning:</strong> Heatmaps, badges, micro-certifications</li>
      <li>📶 <strong>Offline Support:</strong> Works without internet using PWA & TensorFlow Lite</li>
      <li>🔊 <strong>Zero Literacy UI:</strong> Voice navigation, big visuals, auto-transcription</li>
    </ul>
  </section>
  <section id="contact">
    <h2>Contact</h2>
    <p>Email: <a href="mailto:team@vidyai.org">team@vidyai.org</a></p>
    <p>GitHub: <a href="https://github.com/Vankalameghana/hack" target="_blank">Project Repo</a></p>
  </section>
  <footer>
    <p>&copy; 2025 VidyAI++. All rights reserved.</p>
  </footer>
</body>
</html>
"""

display(HTML(html_code))